travis:
  secure:
    BINSTAR_TOKEN: MujpcIZ+m4yU0HebrMikhMhQJfdnkwLx4RunKOazYLvxr9etbP2x9RBb+0GeZJuzZaaOnaLuluXobLn6VlnxZF5eq5C94ZxEei8/TK35Gi5VIdVwaX2eLdxzqkUtactJGTzrMROhY1qdvuB8A0bWPmA7PyWmJIdRXhP4DwQZOmx6U4swYDE85cKTBfB+zTpfJlE8jwmdzwElDEMxl8BSXJmnPzrpCGVfSDXzLQOI3VwTjKmaoYaUtr82aTWYyWqNG0iq/iSrvSW9TFYwpa3I1WLwLfWAgKggbIvpYswkcEuznCUyU40Umgwp+PtCiRDRA4jhdNbjmQcWCznG27EjDOuY3Qywih9SUg9b/HdAM0/uzx3GtUC7ZkhssHMhPMhg5aDzQFyQ9k6oitkw19vXCUVeL1y+KoWTrhnWntmxNHm9eqLaOWPAi6QmoaTp5A7lOIR9vz3ub7CNYQH0MXR8hxQJiH3BSWTIeUPRDDeENxAyEuAIf3L4htVjvhg5mc+IZbMG5vWwu+0SQrVNkY98cfqVKkbt18Chmc8nqGs19gkudVBcwl37v9BvrfJ+sSoTCnDYbzCWZAs8Q3EOLpV52Gd4EkpXGDfgZpGuEusFQkxwriGIrHBbKx4gKcRzah5ntEJ4IpXbRVcaNAUHVOWd2lSNnj3MD1EALppsZQRC86M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
